import { getSupabase, saveReport, createIssue } from './src/lib/supabase';
import { generateAutoReport } from './src/lib/report-generator';

async function backfill() {
  const sb = getSupabase();
  if (!sb) {
    console.error('Failed to init Supabase client');
    process.exit(1);
  }

  const { data: convos, error } = await sb
    .from('conversations_852')
    .select('*');

  if (error || !convos) {
    console.error('Failed to fetch conversations:', error);
    process.exit(1);
  }

  console.log(`Found ${convos.length} conversations to process for auto-topics.`);

  for (const convo of convos) {
    let rawMessages = convo.messages;
    if (typeof rawMessages === 'string') {
        try { rawMessages = JSON.parse(rawMessages); } catch (e) {}
    }
    const messages = Array.isArray(rawMessages) ? rawMessages : [];
    if (messages.length < 2) {
      console.log(`Skipping empty convo ${convo.id}`);
      continue;
    }

    const { data: existingReport } = await sb.from('reports_852').select('id').eq('conversation_id', convo.id).maybeSingle();
    
    // Process them through the LLM regardless of length just to backfill reports & topics
    console.log(`Processing ${convo.id} with ${messages.length} messages...`);
    
    try {
      const reviewData = await generateAutoReport(messages) as any;
      if (reviewData) {
        if (!existingReport) {
          // Manually insert into reports_852 via imported function
          await saveReport(convo.id, messages, reviewData, convo.identity_key || undefined, { autoGenerated: true, backfilled: true });
        }

        // Auto topic
        if (typeof reviewData.completude === 'number' && reviewData.completude >= 4) { // lowering threshold to 4 for backfill
          console.log(`✅ Passed threshold (${reviewData.completude}). Creating Topic...`);
          const title = reviewData.titulo || reviewData.title || 'Discussão Relevante';
          const body = reviewData.resumo || 'Resumo inserido automaticamente.';
          const category = reviewData.category || reviewData.categoria || 'Operacional';
          await createIssue(title, body, category, 'ai_report');
        } else {
          console.log(`❌ Skipped topic. Score ${reviewData.completude} < 4`);
        }
      }
    } catch (e) {
      console.error('Error generating report for convo', convo.id, e);
    }
  }
}

backfill().then(() => console.log('Backfill Complete!'));
