import { saveConversation, getConversations, saveReport, createIssue, getSupabase } from '@/lib/supabase';
import { getCurrentUser } from '@/lib/user-auth';
import { summarizeConversation, saveConversationSummary } from '@/lib/conversation-memory';
import { createInteractionHash, getIdentityKey } from '@/lib/session';
import { generateAutoReport } from '@/lib/report-generator';

export async function POST(req: Request) {
  try {
    const { messages, title, sessionHash, existingId, clientConversationId } = await req.json();
    if (!Array.isArray(messages)) {
      return Response.json({ error: 'messages é obrigatório' }, { status: 400 });
    }

    // Dual-persistence Document Pipeline: Sanitize DB entries and upstream AI pipeline
    const { scanForPII, sanitizeText } = require('@/lib/pii-scanner');
    const processedMessages = messages.map(msg => {
      if (msg.role === 'user' && typeof msg.content === 'string') {
        const findings = scanForPII(msg.content);
        if (findings.length > 0) {
          return {
            ...msg,
            rawContent: msg.content,
            content: sanitizeText(msg.content, findings)
          };
        }
      }
      return msg;
    });

    const user = await getCurrentUser();
    const identityKey = getIdentityKey(sessionHash, user?.id);
    const interactionHash = createInteractionHash();

    const id = await saveConversation(processedMessages, title, identityKey || undefined, existingId, {
      clientConversationId: typeof clientConversationId === 'string' ? clientConversationId : null,
      interactionHash,
      lastSyncedAt: new Date().toISOString(),
      userEmail: user?.email || null,
      userDisplayName: user?.display_name || null,
    });

    if (!id) return Response.json({ error: 'Supabase não configurado' }, { status: 503 });

    const lastMessage = messages[messages.length - 1];
    const shouldRefreshSummary = messages.length >= 4 && lastMessage?.role === 'assistant' && (messages.length === 4 || messages.length % 6 === 0);

    let reportTriggered = false;

    if (shouldRefreshSummary) {
      const summary = await summarizeConversation(messages);
      if (summary) {
        await saveConversationSummary(id, summary);
      }
      
      // Auto-extract and Upsert Report
      const reviewData = await generateAutoReport(messages);
      if (reviewData) {
        const sb = getSupabase();
        let existingReport = null;
        if (sb) {
          const { data } = await sb.from('reports_852').select('id').eq('conversation_id', id).maybeSingle();
          existingReport = data;
        }

        await saveReport(id, messages, reviewData, identityKey || undefined, { autoGenerated: true });
        reportTriggered = true;

        // Auto-Topic Creation if this is the FIRST time the report is generated
        if (!existingReport && typeof reviewData.completude === 'number' && reviewData.completude >= 6) {
          const title = reviewData.title || 'Relato Operacional';
          const body = reviewData.resumo || 'Resumo automático processado pela Inteligência.';
          const category = reviewData.categoria || reviewData.category || 'Outros';
          await createIssue(title, body, category, 'ai_report');
        }
      }
    }

    return Response.json({ id, reportTriggered, identityKey, interactionHash });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Erro interno';
    return Response.json({ error: msg }, { status: 500 });
  }
}

export async function GET(req: Request) {
  const user = await getCurrentUser();
  const { searchParams } = new URL(req.url);
  const sessionHash = searchParams.get('sessionHash');
  const identityKey = getIdentityKey(sessionHash, user?.id);
  const convos = await getConversations(50, identityKey || undefined);
  return Response.json({ conversations: convos });
}
